# Run: docker-compose up --build -d
version: "3.8"
services:
  backend:
    build:
      context: .
      target: "develop"
    ports:
      - "80:80"
    volumes:
      - ".:/root"
      - /vendor # Ignore vendor
    command: /bin/sh -c "go run main.go"